### ISSUE TITLE
Designers Catalog Information

### ISSUE THREAD

**Issue by vv-monsalve** [smc/Gayathri#5]
Taken from the FB checks performed after PR [#2573](https://github.com/google/fonts/pull/2573) was updated pointing at [Version 1.110-2](https://gitlab.com/smc/fonts/gayathri/-/tags/Version1.110-2).

This information is intended to feed the Designers section in the [Specimen page](https://fonts.google.com/specimen/Gayathri) of each font in Google Fonts. Please provide us with a bio text of SMC of 100 to 250 characters length extension and a 100*100 px png image.

A good reference of the bio could be [Boutros](https://github.com/google/fonts/blob/master/catalog/designers/boutrosfonts/bio.html).

<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb: Designer is listed with the correct name on the Google Fonts catalog of designers?</summary>

* [com.google.fonts/check/metadata/designer_profiles](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/designer_profiles)

* 🔥 **FAIL** Designer SMC listed a Google Plus link on the catalog, but that service is not available anymore. Please update the webpage link. [code: google-plus]
* 🔥 **FAIL** Designer SMC still does not have an avatar image. Please provide one. [code: missing-avatar]

</details>

**Comment by vv-monsalve** [comment]
This information could include one entry for SMC and another for Binoy Dominic information. 
The requirements would be the same for each one: bio text 100 to 250 characters length extension and a 100*100 px png image

**Comment by santhoshtr** [comment]
SMC
------

Swathanthra Malayalam Computing (SMC) is a free software collective engaged in development, localization, standardization and popularization of various Free and Open Source Softwares in Malayalam language.

Website: https://smc.org.in
Profile image:  ![smc-logo-100x100](https://user-images.githubusercontent.com/161672/106711811-13130e00-661e-11eb-83af-e609916fbcbf.png)

Binoy Dominic
------------------
Binoy Dominic is a graphic designer from India focusing on Malayalam lettering, typesetting and logo designs. He designed Gayathri Malayalam typeface in collaboration with Swathanthra Malayalam Computing organization.

Website: https://binoydominic.com/
Image: ![Binoy](https://user-images.githubusercontent.com/161672/106713042-dea05180-661f-11eb-85c4-583c53f69cf5.png)
